### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by Reckless-Satoshi** [santochibtc/robosatsCharts#1]
We should add a requirements.txt on the root directory so it is easy to get an environment running with all of the required libraries.

Example requirements.txt
```
matplotlib==3.7.1
numpy==1.22.0
pandas==2.0.0
seaborn==0.12.2
```

Then we just need to run `pip install requirements.txt` to get started

**Comment by santochibtc** [comment]
done, thanks :)
