### ISSUE TITLE
Script formatting and pre-commit

### ISSUE THREAD

**Issue by Reckless-Satoshi** [santochibtc/robosatsCharts#4]
We could use Black and a pre-commit hook to automatically make the code pretty before every commit. An example of usage can be found on the main RoboSats repo:

https://github.com/Reckless-Satoshi/robosats/blob/ee8becebd9fc9444587fedf8fc685e2085c4bfec/.pre-commit-config.yaml#L59-L66

Devs could then `pip install pre-commit; pre-commit install;` . Everytime a new commit is made, the code will be automatically formatted to standard.

**Comment by santochibtc** [comment]
Thanks @Reckless-Satoshi, I have fix the format of the code with Black
